name: tea
channels:
  - conda-forge        
dependencies:
  - python=3.8
  - matplotlib=3.7.5
  - numpy=1.24.4
  - opencv=4.10.0=*headless*    
  - pillow=10.4.0
  - requests=2.32.3
  - scipy=1.10.1
  - timm=1.0.15                  
  - pytorch=2.2.2                
  - torchvision=0.17.2
